name: Terraform CI

on:
    push:
        branches: main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: Code checkout
            uses: actions/checkout@v4 

          - name: Install terraform
            uses: hashicorp/setup-terraform@v3
     
          - name: Terraform format
            run: terraform fmt

          - name: Linter
            uses: terraform-linters/setup-tflint@v1

    security:
      needs: [lint]
      runs-on: ubuntu-latest
      steps:
        - name: Code checkout
          uses: actions/checkout@v4 
        - name: Install terraform
          uses: hashicorp/setup-terraform@v3
        - name: Checkov
          uses: bridgecrewio/checkov-action@master
          with:
            soft_fail: true
        - name: tsec
          uses: aquasecurity/tfsec-action@v1.0.0
          with:
            soft_fail: true

    terraform:
      needs: [lint, security]

      runs-on: ubuntu-latest

      steps:
        - name: Code checkout
          uses: actions/checkout@v4 
        - name: Install terraform
          uses: hashicorp/setup-terraform@v3
        - name: Terraform init
          run: terraform init
          env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        - name: Create Plan
          run: terraform plan -out main.tfplan 
          env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        - name: Apply Plan
          if: github.ref == 'refs/heads/main'
          run: terraform apply --auto-approve
          env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}